export const LOAD_IMAGES_PENDING = 'LOAD_IMAGES_PENDING';
export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
export const LOAD_IMAGES_FAIL = 'LOAD_IMAGES_FAIL';
export const UPDATE_HIRED_WORKERS = 'UPDATE_HIRED_WORKERS';
export const REMOVE_WORKER = 'REMOVE_WORKER';
